[package]
name = "dpf"
version = "1.0.0"
resolver = "2"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

[features]
examples = []

[dev-dependencies]
tokio-test = "0.4"
